export { default as kakaopay } from './kpay_a.jpeg';
export { default as kakaoMap } from './kakao-map.webp';
export { default as naverMap } from './naver-map.webp';
export { default as tMap } from './tmap.jpeg';
export { default as shuttleBus1 } from './shuttle_bus_1.jpeg';
export { default as shuttleBus2 } from './shuttle_bus_2.jpeg';
export { default as shuttleBus3 } from './shuttle_bus_3.jpeg';
export { default as shuttleBus4 } from './shuttle_bus_4.jpeg';
export { default as introImg } from './door.png';
